### ISSUE TITLE
Update documentation on unsupported API based on latest/last changes

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-legacy-components#87]
Based on outcome from following issues:
- [ ] #80 - how to handle attach-detach listener migration when not used as lambda
- [ ] #57 - if `ContextClickEvent` support is done - maybe mention it. If not, should be listed as _not-supported_
- [ ] #25 - if `LayoutClickEvent` support done - maybe mention it. If not, should be listed as _not-supported_
- [ ] #84 - if legacy shortcuts API support is done -  mention it. The API is already mentioned as _not-supported_.
- [ ] #70 - couple of FW internal methods are not added back and it would make sense to list out all the legacy classes and what to do about them: updating imports or something else - what ?
  - The missing internal methods are `writeDesign`, `readDesign` and `getRpcManager`
